/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiEndConversationRouteImport } from './routes/api/end-conversation'
import { Route as ApiCreateConversationRouteImport } from './routes/api/create-conversation'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEndConversationRoute = ApiEndConversationRouteImport.update({
  id: '/api/end-conversation',
  path: '/api/end-conversation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreateConversationRoute = ApiCreateConversationRouteImport.update({
  id: '/api/create-conversation',
  path: '/api/create-conversation',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/create-conversation': typeof ApiCreateConversationRoute
  '/api/end-conversation': typeof ApiEndConversationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/create-conversation': typeof ApiCreateConversationRoute
  '/api/end-conversation': typeof ApiEndConversationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/create-conversation': typeof ApiCreateConversationRoute
  '/api/end-conversation': typeof ApiEndConversationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/create-conversation' | '/api/end-conversation'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/create-conversation' | '/api/end-conversation'
  id: '__root__' | '/' | '/api/create-conversation' | '/api/end-conversation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiCreateConversationRoute: typeof ApiCreateConversationRoute
  ApiEndConversationRoute: typeof ApiEndConversationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/end-conversation': {
      id: '/api/end-conversation'
      path: '/api/end-conversation'
      fullPath: '/api/end-conversation'
      preLoaderRoute: typeof ApiEndConversationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/create-conversation': {
      id: '/api/create-conversation'
      path: '/api/create-conversation'
      fullPath: '/api/create-conversation'
      preLoaderRoute: typeof ApiCreateConversationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiCreateConversationRoute: ApiCreateConversationRoute,
  ApiEndConversationRoute: ApiEndConversationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
